builds:
  2a5e54050d90728807878c3eb95cd4c5f41c4c161a6ff761aa3711d9e71b5f75:
    version: 2a5e54050d90728807878c3eb95cd4c5f41c4c161a6ff761aa3711d9e71b5f75
    blobstore_id: adc88f86-bd64-4d7c-7307-110d4b4f913c
    sha1: sha256:da7f7ce2d64a5d35e039a573917872aeeee84d0ac805388373b9bc1dec95b450
  3b92df968c9c0e5417fc6fb7aa1a808363449492:
    version: 3b92df968c9c0e5417fc6fb7aa1a808363449492
    blobstore_id: b98b7afb-2764-4316-432c-f7fe8665757b
    sha1: 00afbd80da7d01288958c5213eac1e589aa123a9
  63959f84a0dc7fd2232f7bbab6e81197f5964fcf:
    version: 63959f84a0dc7fd2232f7bbab6e81197f5964fcf
    blobstore_id: 0a59aefd-6dbe-4399-46b0-323cdce1867a
    sha1: 148c01af98aa8a0cda319dc0706e0c2520ba1e28
  76eb24f18cb2ec365065d62b04571ee24a5631be:
    version: 76eb24f18cb2ec365065d62b04571ee24a5631be
    blobstore_id: 85054ad5-7291-4bcc-4097-c805095bbdcc
    sha1: 494b81134b9ba7a7ef55a05c3b18130365a45642
  ed5ca3b973d181a2418b190bf159a425fbc265fe9cb117ca4957ef995a888e6f:
    version: ed5ca3b973d181a2418b190bf159a425fbc265fe9cb117ca4957ef995a888e6f
    blobstore_id: 5041c078-675b-4ecc-4d06-c83efb8d062f
    sha1: sha256:cf9d40b587a1300d88f59fd6ae60defd1fed4c5682be6b0d94023fb5a6596535
  f71f41442b6d75972edff3108a5c1b08647a61f416fd9a0b7be720347042b452:
    version: f71f41442b6d75972edff3108a5c1b08647a61f416fd9a0b7be720347042b452
    blobstore_id: c1e7d901-37f9-441d-4808-d9843003c4fd
    sha1: sha256:5e16536d99cda7c580edd1bd3052a51aa28bc14de9a29a8ac4fd1511a5765247
format-version: "2"
