busybox/busybox-1.37.0.tar.bz2:
  size: 2565764
  sha: sha256:3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4
docker/docker-compose-linux-x86_64:
  size: 75602664
  object_id: 46eec8be-ab67-49e3-56dc-377c42784619
  sha: sha256:a55a8cd4ef103aac282812554e531aac8df7e914a287ee81e14d695556a22902
docker/docker.tgz:
  size: 33224188
  object_id: 1c5adabb-f1ff-4db3-63da-9fd471284608
  sha: sha256:1d397872e0e9b36cc82cf3f2574b633dc3537ec9f8c5cc61aa1e1f99b7e20d8b
harbor-common/config-utils:
  size: 8789280
  object_id: 34253e28-e6ac-476d-6539-16294c69afcf
  sha: sha256:9cce6e90be2c98c043ef7d334279aff028fb9da4b5a743a98a5fe1df75fb9ab5
harbor/harbor-offline-installer-latest.tgz:
  size: 670694110
  object_id: 13674d6e-a1d0-4170-5b7d-ea718792f56b
  sha: sha256:198bcefa594007186a265cf2513a4ec5f9419c6995e3a02bc81cac8fa17dede3
nfs-common/nfs-common.tgz:
  size: 3476405
  object_id: 146e2371-b423-45f9-410b-40bf3feab21f
  sha: sha256:4aa9478fa85a82c328c9f8098e12c8602dac4edbf2d9fa571c12a6481d61c7d2
python/Python.tgz:
  size: 17539408
  object_id: ecd45b0a-b168-49b5-78bf-e63ba5b8320d
  sha: sha256:da3080e3b488f648a3d7a4560ddee895284c3380b11d6de75edb986526b9a814
smoke-test/smoke-test:
  size: 9079648
  object_id: d142fbb1-7b19-4eba-6fe5-e758b6f670ca
  sha: sha256:c2e89a07e7e2dca2755353e7f81fdf1ce4dab919049bc0944ca1c55aedd3e50d
wavefront/harbor-wavefront-bundle.tgz:
  size: 396318438
  object_id: 645857d1-4799-4414-5c58-4af1a1af7620
  sha: sha256:9ab28b7d779679b143c3ae8c29a7fb07b7cd63a04dc6130a46a49f8c7f441f92
