docker/docker-17.06.2-ce.tgz:
  size: 29704322
  sha: 2a4206fea5d3d3f4373e13569538522417e2c9d3
docker/docker-compose-Linux-x86_64-1.16.1:
  size: 8855632
  sha: e2c7c848e1fa388a2e5b8945fdb2660bf8d8adb1
harbor/harbor-offline-installer-latest.tgz:
  size: 817725606
  sha: eeeea982e6d515a96b6e74f1f525ea843db820d9
library/openssl-1.0.2l.tar.gz:
  size: 5365054
  sha: b58d5d0e9cea20e571d903aafa853e2ccd914138
