docker/docker-18.06.0-ce.tgz:
  size: 43803207
  sha: 2a06bab62d1d5cf083542048cec555cc735ff2b7
docker/docker-18.09.2.tgz:
  size: 48020699
  sha: d33f91b367f6a877eb937c3c38d001494ec1d581
docker/docker-compose-Linux-x86_64:
  size: 11750136
  sha: 9303600664184658b7124d0a65f9e12a4d672708
docker/docker-compose-Linux-x86_64-1.16.1:
  size: 8855632
  sha: e2c7c848e1fa388a2e5b8945fdb2660bf8d8adb1
go/go1.9.2.linux-amd64.tar.gz:
  size: 104247844
  sha: 94c889e039e3d2e94ed95e8f8cb747c5bc1c2b58
harbor/harbor-offline-installer-latest.tgz:
  size: 552852530
  sha: 3c1e901a8a3e7f86bfccfce30c2de131a183e7b5
nfs-common/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-common/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  sha: 57d69f44f3e058e48a7b79595d36076eb21f5942
nfs-common/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-common/nfs-common_1.2.8-9ubuntu12_amd64.deb:
  size: 184538
  sha: 2977e5a1e86615e268cc518f04c9dd2cc832b263
nfs-common/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
python/Python-2.7.15.tgz:
  size: 17496336
  sha: c9750707d127d39a6868e1e55f7cd8c7be006b89
smoke-test/smoke-test:
  size: 6285371
  sha: f615215c8dd9a39e81edc06edb3db864c10ba2c5
wavefront/harbor-wavefront-bundle-1.8.0.tar:
  size: 639023104
  sha: 0c890744c8294a17b5ef115647d800b338f6f522
