builds:
  02603c7ce98a00357ee57857327aea1460bff5fe9516f95c09c671ceadd34eeb:
    version: 02603c7ce98a00357ee57857327aea1460bff5fe9516f95c09c671ceadd34eeb
    blobstore_id: 2cf225ed-d712-462f-68d6-7ca8be0dcbca
    sha1: sha256:a18714996661ccc79fc2725ab8640d12e5c2d14e9c935ec2778935d054e61bc8
  03043c3d2fa10638aac79b5ff27ece4d7ce5d3af:
    version: 03043c3d2fa10638aac79b5ff27ece4d7ce5d3af
    blobstore_id: f00a329c-e841-42c5-62b5-210238e3d40e
    sha1: 66f359ee97346395b8a28b2bad11c30acb4f0372
  cb0ea0d494d6563695e722ed6fc4db18c9d5a093:
    version: cb0ea0d494d6563695e722ed6fc4db18c9d5a093
    blobstore_id: 0576792b-a4e2-4bee-6c2f-516469c58578
    sha1: 5086aab4f0d2e3aab01f853cdde8ceca6fca58d3
  d7b241fdd291a9fdf89629f13636d1941a2d499885e6f603fd75d2d1a646b9fc:
    version: d7b241fdd291a9fdf89629f13636d1941a2d499885e6f603fd75d2d1a646b9fc
    blobstore_id: dd9cad8c-a93e-46b6-7bad-89d6f210c39a
    sha1: sha256:f50aa281e93b5af3edb1650289a0850264516fa078827a95f43671313a1c2c53
format-version: "2"
